---
name: ci
on: [push, pull_request]

jobs:
  yell:
    name: yell
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List files changed
        run: |
          ls
          git status
          git log
